---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(F,T,T,T,T)
class(aLogical)
```

```{r}
sum(aLogical)
```

```{r}
studentMajors <- factor(c("經濟系","經濟系","法律系"))

typeof(studentMajors)
levels(studentMajors)
```

```{r}
studentMajors
```


```{r}
birthplace <- factor(c("台中","台中","台北","台北","台北"))

class (birthplace)
factor(birthplace)
levels(birthplace)
as.integer(birthplace)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger)
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger)
```

```{r}
sum(trueInteger)
```

```{r}
library(lubridate)
```


```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
typeof(dtObject)
```

```{r}
as.double(dtObject)
```

