---
title: '2019-03-27'
author: "林茂廷"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObject
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
```


```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```

```{r}
class(LisbonDateTime)
typeof(LisbonDateTime)
as.double(LisbonDateTime)
as.double(twDateTime)
```

```{r}
googletime<-(mdy_hms("3/14/2019 8:18:47"))
googletime
```

```{r}
date1<-ymd("2018-09-11")
date1
date2<-mdy("March 3, 2019")
date2
```

```{r}
class(date1)
class(date2)
typeof(date2)
as.double(date1)
as.double(date2)
```

```{r}
as.double(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))
as.integer(ymd("2019-03-11"))
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
a-b

aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```

```{r}
a+bL
aL+bL
a-bL
aL-bL
a*bL
aL*bL
```

```{r}
class(a+bL)
class(aL+bL)
```

```{r}
a+4
```

```{r}
c<--4
a+c
```

```{r}
a^b
a %% b
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

twDateTime+1
```

```{r}
dt1<-ymd("2019-08-11")
dt2<-ymd("2000-02-01")
dt1-dt2

A<-dt1-dt2
class(A)
as.difftime(A)
```

```{r}
startingDate = ymd("2000-02-17")
```

```{r}
startingDate + years(1)
```

```{r}
startingDate + dyears(1)
```

```{r}
x <- 5
y <- 7

x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x >= y
x == y
x != y

x = y
x
```
```{r}
x2 < y2
x2 == y2
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")

y3 == x3
x3 != y3
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
y4 %in% x4
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
x2
y2
x2 == y2
is.na(x2)
is.na(y2)
```

```{r}
sum(x2)
sum(x2,na.rm=F)
sum(x2,na.rm=T)
```

```{r}
0/0
```

