---
title: '2019-04-24'
author: "林茂廷"
date: "4/24/2019"
output: html_document
---

```{r}
Vec1 <- c(1:6)
Vec1
```

```{r}
Mat1 <- matrix(
  c(2:7), 2,3
)
Mat1
```

```{r}
class(Mat1)
typeof(Mat1)
```

```{r}
Mat1
Mat1[[2]]
```

```{r}
Mat2 <- matrix(
  c("a","b","c","d"), 2, 2
)
Mat2
```

```{r}
class(Mat2)
typeof(Mat2)

Mat2[[3]]
Mat2[c(F,F,T,F)]
Mat2[c(1,4)]
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
class(StuDF)
typeof(StuDF)
```

```{r}
StuDF[["姓名"]][[3]]
```

```{r}
class(StuDF$姓名)

StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
class(StuDF2$姓名)
```

```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```

```{r}
LETTERS # R內設元素值為英文字母群的character vector
chosenLETTERS <- LETTERS[1:15]

matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```

```{r}
chosenLETTERS[8]
matObj1[8]
```

```{r}
matObj1
matObj1[3,2] 
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
matObj1[c(4,6,8,9)]
```

```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) # 轉成小寫
toupper(m) # 轉成大寫
```

```{r}
matObj1
matObj1[c(1,4),c(2,3)]
```

```{r}
matObj1[c(T,F,F,T,F),c(F,T,T)]
```

```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```

```{r}
class(classSurvey)
```

取出性別跟本學期學分數的欄位
從dataframe視覺角度
```{r}
classSurvey[,4:5]
```

```{r}
classSurvey[c(1:60),c(4,5)]
classSurvey[,c(4,5)]
```

