---
title: '2019-05-15'
author: "林茂廷"
date: "5/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)

Vector1
```

```{r}
Vector1[["名稱4"]]
```

## colnames/ rownames

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```

只改col2的名稱
```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
StuDF2

```
 

改col2,3的名稱
```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grade")
colnames(StuDF2)
StuDF2

rownames(StuDF)[[2]] <- "yes"
rownames(StuDF)
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b[["元素3"]] <- "False"
b[[5]] <- 7
b
```

```{r}
b$元素2 <- "Say No"
b
```

```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
names(b)
names(b)[[4]] <- "hey"
names(b)
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```


```{r}
library(lubridate)
ymd(exData3$期間) -> exData3$期間
class(exData3$期間)

#or
#```{r}
#as.Date(exData3$期間) -> exData3$期間
#class(exData3$期間)
```


```{r}
exData3$isAsiaCrisis <- ymd("1997-06-01") <= exData3$期間 &
  ymd("1998-12-01") >= exData3$期間
isAsiaCrisis
exData3
names(exData3)
```


```{r}
exData3[isAsiaCrisis,]
exData3[exData3$isAsiaCrisis==T ,]

#[直,橫]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
a <- transcriptDataFinal$學號=="92aS67fee"
transcriptDataFinal[a,]
```

