---
title: '2015-05-22'
author: "林茂廷"
date: "5/22/2019"
output: html_document
---

## midterm 6.2

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```

```{r}
(invoiceList$訂單時區=="America/New_York") -> nyLogical
(invoiceList$訂單時區=="Asia/Taipei") -> tpLogical

invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

library(lubridate)
ymd_hms(invoiceList$`訂單時區之下單時間`[nyLogical],
          tz="America/New_York") -> nyDateTime

invoiceList$UTC時間[nyLogical] <-
  with_tz(nyDateTime,tzone="UTC")

ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical],
          tz="Asia/Taipei") -> tpDateTime
invoiceList$UTC時間[tpLogical] <-
  with_tz(tpDateTime,tzone="UTC")

invoiceList 
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
```

```{r}
a <- ymd_hms("1973-02-21 12:05:22")
with_tz(a,tz="Asia/Taipei")

ymd_hms_tzChange <- function(x,y,z){
  trueTime <- ymd_hms(x,tz=y)
  changeTime <- with_tz(trueTime,tzone=z)
  return(changeTime)
}

ymd_hms_tzChange("1973-02-21 12:05:22","UTC","Asia/Taipei")
```

```{r}
(invoiceList$訂單時區=="America/New_York") -> nyLogical
(invoiceList$訂單時區=="Asia/Taipei") -> tpLogical

invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

library(lubridate)
ymd_hms_tzChange(invoiceList$`訂單時區之下單時間`[nyLogical],
        "America/New_York",
        "UTC") -> invoiceList$UTC時間[nyLogical]

ymd_hms_tzChange(invoiceList$`訂單時區之下單時間`[tpLogical],
                 "Asia/Taipei",
                 "UTC") -> invoiceList$UTC時間[tpLogical]

invoiceList 
```

