---
title: '2019-05-29'
author: "林茂廷"
date: "5/29/2019"
output: html_document
---

```{r}
library(lubridate)

now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```

```{r}
now2()
now2() -> xx 
```

```{r}
browseURL("https://www.ntpu.edu.tw")
```

```{r}
textbookURL <- function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science")
}
textbookURL()
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```

```{r}
gpa_fun2("92aS67fee") -> outputValue
outputValue$平均成績
outputValue$成績單
```

```{r}
demand_supply_fun <- function(P,a,b,c,d){
  Qs <- a+b*P
  Qd <- c-d*P
  excessSupply <- Qs-Qd
  return(
    list(
      供給量=Qs,
      需求量=Qd,
      超額供給量=excessSupply
    )
  )
}

demand_supply_fun(1,0,1,10,2)
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
}
```

```{r}
supply_fun2 <- function(P,a,b){
  Qs <- a+b*P
  if(P>=0) {
    return(Qs)
  }
}
supply_fun2(P=-1,0,1)
supply_fun2(P=2,0,1)
```

```{r}
a <-  readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
} else {
  print("a不為負值")
}
```

```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P must be bigger than 0") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```

```{r}
gpa_fun <- function(studentID){
  
  if(studentID %in% transcriptDataFinal$學號){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
    
  return(GPA)
  }else{
    message("ID not found")
  }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```

```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P must be bigger than 0") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P must be equal or bigger than ",-a/b," (aka -a/b)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```

```{r}
5 %% 3
```

```{r}
number <- function(x){
  three <- x %% 3 == 0
  five <- x%% 5 == 0
  if(three & five){
    return("fizzbuzz")
  }else if(three){
    return("fizz")
  }else if(five){
    return("buzz")
  }else{
    message("other situation")
  }
  }
```

```{r}
number(6)
number(10)
number(15)
number(4)
```

```{r}
fizzbuzz <- function(y){
  if(y%%3==0&y%%5==0){
    return("fizzbuzz")
  }else if(y%%3==0){
    return("fizz")
  }else if(y%%5==0){
    return("buzz")
  }else{
    message("other situation")
  }
}
```

```{r}
fizzbuzz(6)
fizzbuzz(10)
fizzbuzz(15)
fizzbuzz(4)
```

```{r}
a <- c(1,3,5)
a>2 # 此邏輯條件產生三個值
if(a>2) {
  print("a大於2")
}
```

```{r}
a
a>2
all(a>2)

if(all(a>2)){
  print("a is bigger than 2")
}
```

```{r}
any(a>2)

if(any(a>2)){
  print("a is bigger than 2")
}
```

