---
title: '2019-06-05'
author: "林茂廷"
date: "6/5/2019"
output: html_document
---

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  a <- x*.alpha+y*.beta
  return(a)
}
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
utility_cobb_douglass(1,2,.beta=0.8,.alpha=0.5)
```

```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
```

```{r}
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
```

```{r}
# 以前5筆學號為sequence_source
studentIds5 <- studentIds[1:5]

for(i in studentIds5){
  print(i) # 印出studentIds5[[i]]
}
```

```{r}
for(i in c(1:5)){
  print(i) 
}
for(i in c(1:5)){
  print(studentIds[[i]]) # 
}
```

```{r}
seq_along(studentIds5)

for (i in seq_along(studentIds5)) {
  print(studentIds5[[i]])
}
```

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
for (i in gmailAddress) {
  print(i)
}
```

```{r}
for (i in c(1:4)) {
  print(gmailAddress[[i]])
}
```

```{r}
for (i in seq_along(gmailAddress)) {
  print(gmailAddress[[i]])
}
```

```{r}
str_detect(gmailAddress[[1]],"@")
```


```{r}
library(stringr)
for (i in seq_along(gmailAddress)) {
  if(str_detect(gmailAddress[[i]],".com")){
    print(gmailAddress[[i]])
  }else{
    print(str_c(gmailAddress,"@gmail.com"))
  }
}
```

