---
title: '2019-06-12'
author: "林茂廷"
date: "6/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load(url("https://www.dropbox.com/s/duh5aaqgl2f5m3z/loopTranscriptData.Rda?raw=1"))
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
studentIds5 <- studentIds[1:5] # 前5筆學號
```

```{r}
studentIds5
seq_along(studentIds5)
```

```{r}
length(studentIds5)
1:length(studentIds5)
```

#針對每個學號做print


```{r}
i <- 1

print(studentIds5[[i]])
```

```{r}
for (i in seq_along(studentIds5)) {
  print(studentIds5[i])
}
```


```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
library(stringr)
for (i in seq_along(gmailAddress)) {
  if(str_detect(gmailAddress[[i]],"gmail.com")){
    print(gmailAddress[[i]])
  }else{
    gmailAddress[[i]] <- str_c(gmailAddress[[i]],"@gmail.com")
    print(gmailAddress[[i]])
  }
}
```

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

```{r}
for (i in seq_along(commitHistory)) {
  print(commitHistory[[i]]$commit$author$name)
}
```

```{r}
for (i in seq_along(commitHistory)) {
  print(
  str_c(
    "Athor is ",
    commitHistory[[i]]$commit$author$name,
    ". Commiter is",
    commitHistory[[i]]$commit$committer$name))
  }
```

```{r}
for (i in seq_along(commitHistory)) {
  author <- commitHistory[[i]]$commit$author$name
  commiter <- commitHistory[[i]]$commit$committer$name
  yes <- author==commiter
  print(commitHistory[[i]]$commit$committer$date[yes=TRUE])
}
```

```{r}
saveCharacter <- vector("character",5)
saveCharacter

saveNumeric <- vector("numeric",5)
saveNumeric

saveLogical <- vector("logical",5)
saveLogical

saveList <- vector("list",5)
saveList
```

```{r}
saveGPA5 <- vector("numeric",length(studentIds5))
saveGPA5
```

```{r}
i <- 1
gpa_fun(studentIds5[[i]]) -> saveGPA5[[i]]
saveGPA5
```


```{r}
#儲存很重要！

for (i in seq_along(studentIds5)) {
  gpa_fun(studentIds5[[i]]) -> saveGPA5[[i]]
}
saveGPA5
```

#Misson 1

```{r}
saveAuthor <- vector("character",length(commitHistory))

for (i in seq_along(commitHistory)) {
  saveAuthor[[i]] <- commitHistory[[i]]$commit$author$name
}
saveAuthor
```

#Mission 2

```{r}
saveCommitter <- vector("character",length(commitHistory))

for (i in seq_along(commitHistory)) {
  saveCommitter[[i]] <- commitHistory[[i]]$commit$committer$name
}
saveCommitter
```

#Mission 3

```{r}
saveDate <- vector("character",length(commitHistory))

for (i in seq_along(commitHistory)) {
  saveDate[[i]] <- commitHistory[[i]]$commit$committer$date
}
saveDate
```

#Expand mission

```{r}
saveSame <- vector("character",length(commitHistory))

for (i in seq_along(commitHistory)) {
  author <- commitHistory[[i]]$commit$author$name
  committer <- commitHistory[[i]]$commit$committer$name
  yes <- author==committer
  commitHistory[[i]]$commit$committer$date -> saveSame

}
saveSame
```

